version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_OUTGOING_USER: username
      MAILDEV_OUTGOING_PASS: password
    ports:
      - "1080:1080"
      - "1025:1025"
